export const CHANGE_SEARCH_RESULT = 'CHANGE_SEARCH_RESULT';

export const REQUEST_CONTACTS_PENDING = 'REQUEST_CONTACTS_PENDING';
export const REQUEST_CONTACTS_SUCCESS = 'REQUEST_CONTACTS_SUCCESS';
export const REQUEST_CONTACTS_FAILED = 'REQUEST_CONTACTS_FAILED';

export const ADD_CONTACT = 'ADD_CONTACT';